import test from 'node:test';
import assert from 'node:assert/strict';
import { associateIssue, workRecords } from '../factory/issue-lifecycle.mjs';
const url = 'https://github.com/example/project/issues/42';
const job = (id, state, source=url) => ({ id, state, task:{title:id, source_url:source}, workflow:{name:'software',steps:['build'],current_step:0}, created_at:id });
test('all-work model deduplicates provider identity, retains every attempt and does not infer remote state or workflow', () => {
  const jobs = [job('a','succeeded'),job('b','running',url.toUpperCase().replace('HTTPS','http')+'/?query=1'),job('c','failed',''),job('d','cancelled',url.replace('42','99'))];
  const issues = [42,43].map(number=>associateIssue({url:url.replace('42',number),title:`Issue ${number}`,state:'open',labels:[{name:'factory:triage'}]},jobs));
  const records = workRecords(jobs,[...issues,issues[0]]);
  assert.equal(records.length,4);
  const linked=records.find(row=>row.identity?.number===42);
  assert.equal(linked.title,'Issue 42');assert.equal(linked.execution_id,'b');assert.equal(linked.state,'running');
  assert.deepEqual(linked.executions.map(item=>item.id),['b','a']);assert.equal(linked.issue.readiness.state,'triage');
  const fresh=records.find(row=>row.identity?.number===43);
  assert.equal(fresh.state,'not_started');assert.equal(fresh.workflow,null);assert.equal(fresh.phase,null);assert.equal(fresh.execution_id,null);
  const outside=records.find(row=>row.identity?.number===99);
  assert.equal(outside.source_status,'not_loaded');assert.equal(outside.issue,null);assert.equal(outside.state,'cancelled');
  assert.equal(records.find(row=>row.key==='local:c').source_status,'local');
  assert.equal(workRecords(jobs,[]).find(row=>row.identity?.number===42).issue,null);
});
